if !has('vim9script')
    finish
endif

vim9script

syntax on

filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

if has('termguicolors')
    set termguicolors
endif

colorscheme custom_colourscheme

if has('gui_running')
    set guioptions-=T
    set guioptions-=m
    set guioptions-=r
    set guioptions-=L
    if has('gui_win32')
        set guifont=Liberation_Mono:h11:cANSI
    else
        set guifont=Liberation\ Mono\ 11
    endif
endif

set relativenumber
set fillchars+=vert:\ 

g:currentmode = {
    'n': 'NORMAL ',
    'v': 'VISUAL ',
    'V': 'V·Line ',
    "\<C-V>": 'V·Block ',
    'i': 'INSERT ',
    'R': 'R ',
    'Rv': 'V·Replace ',
    'c': 'Command ',
}
 

# TODO refactor this function
def g:FileInfo(): string
    var type = &filetype
    var encoding = &fileencoding
    var format = &fileformat
    var result = ''

    if (type != '')
        result = result .. type
    endif

    if (format != '')
        if (result != '')
            result = result .. ' '
        endif 
        result = result .. format
    endif

    if (encoding != '')
        if (result != '')
            result = result .. ' '
        endif 
        result = result .. format
    endif

    return result 
enddef

def g:GitBranch(): string
    if !isdirectory('.git') 
        return ''
    endif
    var gitBranch = substitute(system("git rev-parse --abbrev-ref HEAD"), '\n', '', 'g')

    if (gitBranch != '')
        return 'branch:' .. gitBranch
    endif

    return ''
enddef

set laststatus=2
set statusline=
set statusline+=\ %{currentmode[mode()]}
set statusline+=%F%m\ [%{FileInfo()}]\ 
# set statusline+=%{GitBranch()}\ 
set statusline+=%=
set statusline+=L:%l/%L\ C:%c\ 

nnoremap <SPACE> <Nop>
g:mapleader = " "

nnoremap <silent> <leader>h :wincmd h<CR>
nnoremap <silent> <leader>j :wincmd j<CR>
nnoremap <silent> <leader>k :wincmd k<CR>
nnoremap <silent> <leader>l :wincmd l<CR>
nnoremap <silent> <leader>H :wincmd H<CR>
nnoremap <silent> <leader>J :wincmd J<CR>
nnoremap <silent> <leader>K :wincmd K<CR>
nnoremap <silent> <leader>L :wincmd L<CR>

nnoremap <silent> <leader>s :split<CR>
nnoremap <silent> <leader>v :vsplit<CR>
