if !has('vim9script')
    finish
endif

vim9script

syntax on

filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

colorscheme custom_colourscheme

if has('gui_running')
    set guioptions-=T
    set guioptions-=m
    set guioptions-=r
    set guioptions-=L
    if has('gui_win32')
        set guifont=Liberation_Mono:h11:cANSI
    else
        set guifont=Liberation\ Mono\ 11
    endif
endif

set relativenumber

nnoremap <SPACE> <Nop>
g:mapleader = " "

nnoremap <silent> <leader>h :wincmd h<CR>
nnoremap <silent> <leader>j :wincmd j<CR>
nnoremap <silent> <leader>k :wincmd k<CR>
nnoremap <silent> <leader>l :wincmd l<CR>
nnoremap <silent> <leader>H :wincmd H<CR>
nnoremap <silent> <leader>J :wincmd J<CR>
nnoremap <silent> <leader>K :wincmd K<CR>
nnoremap <silent> <leader>L :wincmd L<CR>

nnoremap <silent> <leader>s :split<CR>
nnoremap <silent> <leader>v :vsplit<CR>
